## Partie B - Pandas et SQL

In [1]:
import pandas as pd
import sqlite3
con = sqlite3.connect('../../data/marketing.db')

In [ ]:
# 7. Charger la table `orders` depuis la base `marketing.db`
orders = pd.read_sql('SELECT * FROM orders', con)

In [5]:
# 8. Lister les 5 premières commandes avec le nom du client
orders_with_customers = pd.read_sql('''
    SELECT o.*, c.name AS customer_name
    FROM orders o
    JOIN customers c ON o.customer_id = c.id
    LIMIT 5
''', con)

orders_with_customers

   id  customer_id  amount  order_date customer_name
0   1            1    39.9  2025-06-01         Alice
1   2            2   120.0  2025-06-02           Bob
2   3            1    59.0  2025-06-03         Alice
3   4            3    80.0  2025-06-04       Charlie
4   5            4    25.0  2025-06-05         Diana

In [6]:
# 9. Calculer le total dépensé par chaque client
total_per_customer = pd.read_sql('''
    SELECT c.id AS customer_id, c.name AS customer_name, SUM(o.amount) AS total_spent
    FROM customers c
    JOIN orders o ON c.id = o.customer_id
    GROUP BY c.id, c.name
''', con)

total_per_customer

   customer_id customer_name  total_spent
0            1         Alice         98.9
1            2           Bob        380.0
2            3       Charlie         80.0
3            4         Diana         25.0
4            5         Ethan         75.5
5           10          Jane        140.0
6           11         Kevin        110.0

In [7]:
# 10. Calculer le panier moyen par ville.
average_basket_per_city = pd.read_sql('''
    SELECT c.city, AVG(o.amount) AS average_basket
    FROM customers c
    JOIN orders o ON c.id = o.customer_id
    GROUP BY c.city
''', con)

average_basket_per_city

        city  average_basket
0      Lille            75.5
1       Lyon           104.0
2  Marseille            80.0
3       Nice           110.0
4      Paris            41.3

In [8]:
# 11. Exporter le rapport en CSV
average_basket_per_city.to_csv('average_basket_per_city.csv', index=False)

In [9]:
# *(Optionnel)* Trouver le top 3 clients par montant total.
top_3_customers = total_per_customer.sort_values(by='total_spent', ascending=False).head(3)
top_3_customers

   customer_id customer_name  total_spent
1            2           Bob        380.0
5           10          Jane        140.0
6           11         Kevin        110.0