## Partie A - Pandas

In [2]:
import pandas as pd

In [5]:
# 1. Charger le fichier `customers.csv`
customers = pd.read_csv('../../data/customers.csv')

customers.head()

   id     name  age       city
0   1    Alice   25      Paris
1   2      Bob   35       Lyon
2   3  Charlie   40  Marseille
3   4    Diana   28      Paris
4   5    Ethan   32      Lille

In [6]:
# 2. Afficher uniquement la colonne `name`.
customers['name']

0       Alice
1         Bob
2     Charlie
3       Diana
4       Ethan
5       Fiona
6      George
7      Hannah
8         Ian
9        Jane
10      Kevin
11      Linda
12       Mike
13       Nina
14      Oscar
Name: name, dtype: object

In [7]:
# 3. Lister les clients de Paris.
customers[customers['city'] == 'Paris']

   id   name  age   city
0   1  Alice   25  Paris
3   4  Diana   28  Paris
8   9    Ian   38  Paris

In [8]:
# 4. Trier les clients par âge décroissant.  
customers.sort_values(by='age', ascending=False)

    id     name  age        city
6    7   George   45    Bordeaux
2    3  Charlie   40   Marseille
8    9      Ian   38       Paris
12  13     Mike   36    Bordeaux
1    2      Bob   35        Lyon
14  15    Oscar   34  Strasbourg
10  11    Kevin   33        Nice
4    5    Ethan   32       Lille
7    8   Hannah   31  Strasbourg
13  14     Nina   30       Lille
5    6    Fiona   29        Nice
3    4    Diana   28       Paris
9   10     Jane   27        Lyon
11  12    Linda   26   Marseille
0    1    Alice   25       Paris

In [9]:
# 5. Compter combien de clients viennent de chaque ville.  
customers['city'].value_counts()

city
Paris         3
Lyon          2
Marseille     2
Lille         2
Nice          2
Bordeaux      2
Strasbourg    2
Name: count, dtype: int64

In [10]:
# 6. Sauvegarder les clients de Lyon dans `data/lyon_clients.csv`.  
customers[customers['city'] == 'Lyon'].to_csv('../../data/lyon_clients.csv', index=False)

In [11]:
# *(Optionnel)* Lister les clients dont le nom commence par “A”.  
customers[customers['name'].str.startswith('A')]

   id   name  age   city
0   1  Alice   25  Paris